### ISSUE TITLE
matrix-content-scanner does not await the result of sendFile before triggering secure removal

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/matrix-content-scanner#30]
For small files, this is not a problem as sendFile manages to send them all before secure removal executes, but for larger files this can lead to early truncation of the file as `srm` kicks in.

(I'm fairly sure this is happening by  https://github.com/matrix-org/matrix-content-scanner/blob/master/src/handlers.js#L132 not awaiting the call to res.sendFile(), or otherwise using the continuation function `next` that can be passed to sendFile() to handle errors / success)

Original report noted that tcpdumping the requested files, they would occasionally see "0xFF" bytes returned incorrectly, especially in larger files, which is the result of the first part of the `srm` process to securely delete a file.

**Comment by ara4n** [comment]
This is causing some high profile problems.
