### ISSUE TITLE
Scan for large files (> 10MB) failed on timeout

### ISSUE THREAD

**Issue by giomfo** [matrix-org/matrix-content-scanner#35]
The first time I trigger the scan on a new uploaded image (12MB), the request failed on a timeout error.
If I trigger a new scan request on the same url, the media is considered safe and is returned.

Note: this issue is not reproduced when the secure remove is disabled on server side.

I'm wondering whether #30 has been really fixed...

**Comment by babolivier** [comment]
After some investigation, a good solution we could go with to mitigate this issue would be to change the way scans are handled, and instead use this flow:

* MCS receives a file, decrypts it (if necessary) and starts scanning it in a background job
* If the scan (+ removal) completes within `[timeout]` seconds (e.g. 30s), we return the file's data (either encrypted or not, depending on the case) or an error if something failed
* After `[timeout]` seconds (e.g. 30s), if the scan + removal isn't complete yet, return with a URL that the client can periodically poll to check the status of this file
* The client polls the provided URL every `[poll_interval]` seconds, which returns either a message that says that the scan is still ongoing or the results if the scan + removal is complete (i.e. file data in case of success, error in case of failure)

This is likely too much for this task in the current sprint, however while waiting for this solution to be validated and implemented (if it gets there) we could make client wait longer before timing out.

Separately, we considered doing the file removal after sending the response, but there's a point about the fact that we want to make sure that the removal worked and didn't just silently failed, leaving unencrypted versions of sensible files on the disk indefinitely.

**Comment by giomfo** [comment]
Caution: it turns out that "doing the file removal after sending the response" is already what the MCS does.

@babolivier done some tests locally and can confirm that the MCS doesn't wait for the removal to be done before sending the response. This behaviour dates from June 2018 afaict.

**Comment by giomfo** [comment]
this is not reproduced anymore
