### ISSUE TITLE
If configured to allow only certain mimetypes, textual files are going to fail without a scan

### ISSUE THREAD

**Issue by jaywink** [matrix-org/matrix-content-scanner#49]
If the config `acceptedMimeType` is enabled, we will run a check via the https://www.npmjs.com/package/file-type module to get the mime-type of the file.

The particular library works on magic bytes and says:

> This package is for detecting binary-based file formats, not text-based formats like .txt, .csv, .svg, etc.

M-C-S will skip any file that does not get a valid mimetype from this library, which means even if flagging YAML or other text format files into `acceptedMimeType` config, they will be skipped.

**Comment by anoadragon453** [comment]
One potential solution here is to simply use the extension of the file if `file-type` reports it as text?

**Comment by anoadragon453** [comment]
I also notice that `file` on Linux can detect that an SVG named `blah.txt` is actually an SVG, so there may be more powerful libraries out there than `file-type` that can detect text-based filetypes as well.
