### ISSUE TITLE
Consider as optional the mimetype in the file description

### ISSUE THREAD

**Issue by giomfo** [matrix-org/matrix-content-scanner#50]
Hi, a recent change in the attachment description at the Element client level "Remove Redundant mimetype Fields" broke the use of the content scanner in encrypted rooms.
Any scan request fails with the following error because the `mimetype` is missing
```
{
  "info" : "Client error: File type not supported",
  "reason" : "MCS_MEDIA_NOT_CLEAN"
}
```
 The mimetype field has been removed from the `content.file` description, because it was already mentioned in the `content.info`(see [here](
https://github.com/vector-im/element-web/issues/17145).

Suggestion: consider as optional the mimetype in the file description at the content scanner level [here](https://github.com/matrix-org/matrix-content-scanner/blob/main/src/reporting.js#L319). The mimetype is currently checked from the decrypted content too

**Comment by anoadragon453** [comment]
It's worth noting that the client will independently send the `content.file` dictionary from the `m.room.message` event. Thus the content scanner never gets access to the specced `content.info.mimetype` field, only `content.file.mimetype`.

We could only optionally consider `content.file.mimetype`, yet I'd actually go as far to say that we should just completely ignore `content.file.mimetype` altogether, as it's not specced.

As @giomfo says, the mimetype of the actual file is eventually checked via magic bytes, regardless of what the client claims.

**Comment by anoadragon453** [comment]
https://github.com/matrix-org/matrix-content-scanner/pull/51 addresses this issue, and now ignores the field altogether.

**Comment by anoadragon453** [comment]
As noted in https://github.com/vector-im/element-web/issues/17145#issuecomment-894158724, this field actually is currently specced (or at least intended to be), but that there's an open MSC (https://github.com/matrix-org/matrix-doc/pull/2582) to remove it, and clients have been steadily doing so.
