### ISSUE TITLE
antivirus script handling: differentiate between infected and av not available

### ISSUE THREAD

**Issue by MatMaul** [matrix-org/matrix-content-scanner#56]
Currently when the antivirus is not available the file is rejected as infected, which is the good thing to do.

However this result is also cached, which gives us false positive even after the antivirus became available since the result is taken from the cache.

We should use a specific return code for when the antivirus is not avail, and not cache the result in this case.

**Comment by babolivier** [comment]
Will be fixed by https://github.com/matrix-org/matrix-content-scanner/pull/59. DINUM deployment also requires a change in DINUM's antivirus script: https://github.com/matrix-org/matrix-dinsic/pull/829.
